"""partner

Revision ID: 7a59d4ead463
Revises: 801b86be184b
Create Date: 2026-01-12 16:04:23.106163
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '7a59d4ead463'
down_revision: Union[str, None] = '801b86be184b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('partners',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('average_cycle_length', sa.Integer(), nullable=False),
    sa.Column('average_period_length', sa.Integer(), nullable=False),
    sa.Column('cycle_regularity', sa.Enum('regular', 'somewhat_irregular', 'irregular', name='cycleregularity'), nullable=False),
    sa.Column('last_period_start', sa.Date(), nullable=True),
    sa.Column('notification_period_reminder', sa.Boolean(), nullable=False),
    sa.Column('notification_pms_alert', sa.Boolean(), nullable=False),
    sa.Column('notification_ovulation_alert', sa.Boolean(), nullable=False),
    sa.Column('reminder_days_before', sa.Integer(), nullable=False),
    sa.Column('timezone', sa.String(length=50), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_partners_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_partners'))
    )
    op.create_index(op.f('ix_partners_user_id'), 'partners', ['user_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_partners_user_id'), table_name='partners')
    op.drop_table('partners')
    # ### end Alembic commands ###
