"""period_log

Revision ID: 59f0447530ef
Revises: 7a59d4ead463
Create Date: 2026-01-12 17:55:55.398428
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '59f0447530ef'
down_revision: Union[str, None] = '7a59d4ead463'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('period_logs',
    sa.Column('partner_id', sa.Uuid(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('cycle_length', sa.Integer(), nullable=True),
    sa.Column('flow_intensity', sa.Enum('light', 'medium', 'heavy', name='flowintensity'), nullable=True),
    sa.Column('is_predicted', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['partner_id'], ['partners.id'], name=op.f('fk_period_logs_partner_id_partners'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_period_logs')),
    sa.UniqueConstraint('partner_id', 'start_date', name='uq_period_log_partner_start')
    )
    op.create_index(op.f('ix_period_logs_partner_id'), 'period_logs', ['partner_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_period_logs_partner_id'), table_name='period_logs')
    op.drop_table('period_logs')
    # ### end Alembic commands ###
