"""daily_log

Revision ID: 3b6202c178ae
Revises: 59f0447530ef
Create Date: 2026-01-12 22:41:23.563390
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '3b6202c178ae'
down_revision: Union[str, None] = '59f0447530ef'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('daily_logs',
    sa.Column('partner_id', sa.Uuid(), nullable=False),
    sa.Column('log_date', sa.Date(), nullable=False),
    sa.Column('mood', sa.Enum('great', 'good', 'meh', 'rough', 'just_nod', 'pick_your_battles', name='mood'), nullable=True),
    sa.Column('energy_level', sa.Integer(), nullable=True),
    sa.Column('symptoms', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['partner_id'], ['partners.id'], name=op.f('fk_daily_logs_partner_id_partners'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_daily_logs')),
    sa.UniqueConstraint('partner_id', 'log_date', name='uq_daily_log_partner_date')
    )
    op.create_index(op.f('ix_daily_logs_partner_id'), 'daily_logs', ['partner_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_daily_logs_partner_id'), table_name='daily_logs')
    op.drop_table('daily_logs')
    # ### end Alembic commands ###
